name: technitium_dns
services:
  technitium_dns:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: technitium/dns-server:13.0.2
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
    ports:
      - target: 5380
        published: "5380"
        protocol: tcp
      - target: 53
        published: "53"
        protocol: udp
      - target: 53
        published: "53"
        protocol: tcp
      - target: 853
        published: "853"
        protocol: tcp
    restart: unless-stopped
    sysctls:
      net.ipv4.ip_local_port_range: 1024 65000
    volumes:
      - type: bind
        source: /DATA/AppData/technitium-dns-server
        target: /etc/dns
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: "timezone"
      ports:
        - container: "5380"
          description:
            en_us: WebUI HTTP Port
        - container: "53"
          description:
            en_us: DNS Listen Port TCP
        - container: "53"
          description:
            en_us: DNS Listen Port UDP
        - container: "853"
          description:
            en_us: DNS over TLS Port
      volumes:
        - container: /etc/dns
          description:
            en_us: dns config directory.

    container_name: technitium_dns
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: technitium_dns
  author: selcuk9805
  category: Network
  description:
    en_us: Technitium DNS Server is lightweight, open source and fully customizable DNS server.
  developer: Technitium Team
  icon: https://camo.githubusercontent.com/957659b80f5e7552f7d75e705e19ea0452f7c419c5a8bccec5ed9fade2f5d3de/68747470733a2f2f746563686e697469756d2e636f6d2f696d672f6c6f676f2e706e67
  screenshot_link:
    - https://technitium.com/dns/ScreenShot1.png
    - https://technitium.com/dns/ScreenShot2.png
    - https://technitium.com/dns/ScreenShot3.png
  tagline:
    en_us: Technitium DNS Server is lightweight, open source and fully customizable DNS server.
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Memos/thumbnail.png
  tips: {}
  title:
    en_us: Technitium-DNS-Server
  port_map: "5380"