name: softether_vpn
services:
  softether:
    cap_add:
      - NET_ADMIN
    cpu_shares: 90
    command: []
    container_name: softether
    deploy:
      resources:
        limits:
          memory: 960M
    hostname: softether
    image: softethervpn/vpnserver:stable
    labels:
      icon: https://fineproxy.org/wp-content/uploads/2023/09/SoftEther-logo.png
    ports:
      - target: 53
        published: "53"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
      - target: 992
        published: "992"
        protocol: tcp
      - target: 1194
        published: "1194"
        protocol: udp
      - target: 5555
        published: "5555"
        protocol: tcp
      - target: 500
        published: "500"
        protocol: udp
      - target: 4500
        published: "4500"
        protocol: udp
      - target: 1701
        published: "1701"
        protocol: udp
    restart: always
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
      - type: bind
        source: /DATA/AppData/SoftEther/softether_data
        target: /mnt
      - type: bind
        source: /DATA/AppData/SoftEther/softether_log
        target: /usr/local/bin/server_log
      - type: bind
        source: /DATA/AppData/SoftEther/softether_packetlog
        target: /usr/local/bin/packet_log
      - type: bind
        source: /DATA/AppData/SoftEther/softether_securitylog
        target: /usr/local/bin/security_log
    devices: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: softether_vpn
  author: selcuk9805
  category: Network
  description:
    en_us: SoftEther VPN Server is powerful, open source and fully customizable VPN server.
  tagline:
    en_us: SoftEther VPN Server is powerful, open source and fully customizable VPN server.
  developer: SoftEther Team
  icon: https://images.dwncdn.net/images/t_app-icon-l/p/57560db7-7645-4371-9e80-8020bc8bc653/640803930/7240_4-75886064-logo
  tips: {}
  screenshot_link:
    - http://www.softether.org/@api/deki/files/477/=0-03-3-4-1-2.png?size=webview
    - http://www.softether.org/@api/deki/files/478/=0-04-2-4-2.png?size=webview
    - http://www.softether.org/@api/deki/files/479/=0-06-ss1.2.jpg?size=webview
  port_map: ""
  title:
    en_us: SoftEther-VPN-Server
